# Generated by Django 2.0.7 on 2018-07-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='price_large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='price_small',
            field=models.FloatField(),
        ),
    ]
