# Generated by Django 2.0.7 on 2018-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180729_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='has_toppings',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
