# Generated by Django 2.0.7 on 2018-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menu_item_has_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='price_small',
            field=models.FloatField(null=True),
        ),
    ]
