# Generated by Django 2.0.7 on 2018-07-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu_item',
            new_name='menu_items',
        ),
    ]
