# Generated by Django 2.0.7 on 2018-07-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180730_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_items',
            name='has_toppings',
        ),
        migrations.AddField(
            model_name='menu_items',
            name='num_toppings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
