# Generated by Django 2.0.7 on 2018-08-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180730_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('totalCost', models.FloatField()),
                ('items', models.CharField(max_length=64)),
                ('toppings', models.CharField(max_length=64)),
            ],
        ),
    ]
