# Generated by Django 2.0.7 on 2018-08-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='totalCost',
        ),
    ]
